"""add structured address columns to members

Revision ID: 28cff1b0ad6f
Revises: dfbdbd278f9a
Create Date: 2026-08-22 23:21:46.818179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cff1b0ad6f'
down_revision = 'dfbdbd278f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AddressCountry', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('AddressState', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('AddressDistrict', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('AddressCity', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('AddressPincode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('AddressPincode')
        batch_op.drop_column('AddressCity')
        batch_op.drop_column('AddressDistrict')
        batch_op.drop_column('AddressState')
        batch_op.drop_column('AddressCountry')

    # ### end Alembic commands ###
