"""add address locality to members

Revision ID: b46a65f41185
Revises: 28cff1b0ad6f
Create Date: 2026-08-22 23:27:03.832698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46a65f41185'
down_revision = '28cff1b0ad6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AddressLocality', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('AddressLocality')

    # ### end Alembic commands ###
