"""add address suburb to members

Revision ID: c1f63f26d538
Revises: b46a65f41185
Create Date: 2026-08-22 23:29:46.322893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f63f26d538'
down_revision = 'b46a65f41185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AddressSuburb', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('AddressSuburb')

    # ### end Alembic commands ###
