"""add_notes_expected_attendance_to_bookings

Revision ID: c48006d9dfe5
Revises: f3e2a6829c44
Create Date: 2026-09-01 21:54:07.145503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48006d9dfe5'
down_revision = 'f3e2a6829c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ExpectedAttendance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.drop_column('Notes')
        batch_op.drop_column('ExpectedAttendance')

    # ### end Alembic commands ###
