"""Initial schema

Revision ID: dfbdbd278f9a
Revises: 
Create Date: 2026-08-19 12:22:50.807090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbdbd278f9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups',
    sa.Column('BackupID', sa.Integer(), nullable=False),
    sa.Column('BackupDate', sa.DateTime(), nullable=True),
    sa.Column('BackupType', sa.String(length=40), nullable=True),
    sa.Column('FilePath', sa.String(length=255), nullable=True),
    sa.Column('SizeBytes', sa.BigInteger(), nullable=True),
    sa.Column('Verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('BackupID')
    )
    op.create_table('care_cells',
    sa.Column('CareCellID', sa.Integer(), nullable=False),
    sa.Column('CareCellName', sa.String(length=120), nullable=False),
    sa.Column('LeaderID', sa.Integer(), nullable=True),
    sa.Column('AssistantLeaderID', sa.Integer(), nullable=True),
    sa.Column('Location', sa.String(length=255), nullable=True),
    sa.Column('MeetingSchedule', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AssistantLeaderID'], ['members.MemberID'], name='fk_carecell_assistant', use_alter=True),
    sa.ForeignKeyConstraint(['LeaderID'], ['members.MemberID'], name='fk_carecell_leader', use_alter=True),
    sa.PrimaryKeyConstraint('CareCellID')
    )
    op.create_table('communications',
    sa.Column('CommunicationID', sa.Integer(), nullable=False),
    sa.Column('Channel', sa.String(length=40), nullable=True),
    sa.Column('Subject', sa.String(length=200), nullable=True),
    sa.Column('Body', sa.Text(), nullable=True),
    sa.Column('Category', sa.String(length=80), nullable=True),
    sa.Column('ScheduledFor', sa.DateTime(), nullable=True),
    sa.Column('SentAt', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(length=40), nullable=True),
    sa.Column('FlyerPath', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('CommunicationID')
    )
    op.create_table('custom_fields',
    sa.Column('FieldID', sa.Integer(), nullable=False),
    sa.Column('Module', sa.String(length=80), nullable=False),
    sa.Column('FieldName', sa.String(length=80), nullable=False),
    sa.Column('FieldLabel', sa.String(length=120), nullable=True),
    sa.Column('FieldType', sa.String(length=40), nullable=True),
    sa.Column('Required', sa.Boolean(), nullable=True),
    sa.Column('Options', sa.Text(), nullable=True),
    sa.Column('SortOrder', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('FieldID')
    )
    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_fields_Module'), ['Module'], unique=False)

    op.create_table('events',
    sa.Column('EventID', sa.Integer(), nullable=False),
    sa.Column('EventName', sa.String(length=150), nullable=False),
    sa.Column('EventType', sa.String(length=80), nullable=True),
    sa.Column('EventDate', sa.Date(), nullable=True),
    sa.Column('Location', sa.String(length=150), nullable=True),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('EventID')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_EventDate'), ['EventDate'], unique=False)

    op.create_table('google_forms',
    sa.Column('FormID', sa.Integer(), nullable=False),
    sa.Column('FormName', sa.String(length=150), nullable=False),
    sa.Column('FormURL', sa.String(length=255), nullable=True),
    sa.Column('SheetID', sa.String(length=120), nullable=True),
    sa.Column('FieldMapping', sa.Text(), nullable=True),
    sa.Column('TargetModule', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('FormID')
    )
    op.create_table('inventory_items',
    sa.Column('ItemID', sa.Integer(), nullable=False),
    sa.Column('AssetCode', sa.String(length=80), nullable=True),
    sa.Column('AssetName', sa.String(length=150), nullable=False),
    sa.Column('Category', sa.String(length=80), nullable=True),
    sa.Column('Value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('PurchaseDate', sa.Date(), nullable=True),
    sa.Column('AssignedTo', sa.String(length=120), nullable=True),
    sa.Column('Status', sa.String(length=40), nullable=True),
    sa.Column('NextMaintenanceDate', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ItemID')
    )
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_items_AssetCode'), ['AssetCode'], unique=True)

    op.create_table('leadership_roles',
    sa.Column('LeadershipRoleID', sa.Integer(), nullable=False),
    sa.Column('RoleName', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('LeadershipRoleID')
    )
    op.create_table('ministries',
    sa.Column('MinistryID', sa.Integer(), nullable=False),
    sa.Column('MinistryName', sa.String(length=120), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('MinistryID')
    )
    op.create_table('missions',
    sa.Column('MissionID', sa.Integer(), nullable=False),
    sa.Column('MissionName', sa.String(length=150), nullable=False),
    sa.Column('Country', sa.String(length=80), nullable=True),
    sa.Column('MissionType', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('MissionID')
    )
    op.create_table('offerings',
    sa.Column('OfferingID', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ServiceDate', sa.Date(), nullable=True),
    sa.Column('ServiceType', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('OfferingID')
    )
    with op.batch_alter_table('offerings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offerings_ServiceDate'), ['ServiceDate'], unique=False)

    op.create_table('outreach_programs',
    sa.Column('OutreachID', sa.Integer(), nullable=False),
    sa.Column('ProgramName', sa.String(length=150), nullable=False),
    sa.Column('OutreachDate', sa.Date(), nullable=True),
    sa.Column('Location', sa.String(length=150), nullable=True),
    sa.Column('Organizers', sa.String(length=255), nullable=True),
    sa.Column('TeamMembers', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('OutreachID')
    )
    op.create_table('permissions',
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.Column('PermissionName', sa.String(length=120), nullable=False),
    sa.Column('ModuleName', sa.String(length=80), nullable=False),
    sa.Column('Action', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('PermissionID'),
    sa.UniqueConstraint('ModuleName', 'Action', name='uq_permission_module_action')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_ModuleName'), ['ModuleName'], unique=False)

    op.create_table('roles',
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('RoleName', sa.String(length=80), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('RoleID'),
    sa.UniqueConstraint('RoleName')
    )
    op.create_table('training_courses',
    sa.Column('CourseID', sa.Integer(), nullable=False),
    sa.Column('CourseName', sa.String(length=120), nullable=False),
    sa.Column('CourseLevel', sa.String(length=80), nullable=True),
    sa.Column('MandatoryForLeadership', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('CourseID')
    )
    op.create_table('visitors',
    sa.Column('VisitorID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=80), nullable=False),
    sa.Column('LastName', sa.String(length=80), nullable=True),
    sa.Column('Phone', sa.String(length=40), nullable=True),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('VisitDate', sa.Date(), nullable=True),
    sa.Column('InvitedBy', sa.String(length=120), nullable=True),
    sa.Column('PrayerRequests', sa.Text(), nullable=True),
    sa.Column('FollowupStatus', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('VisitorID')
    )
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitors_VisitDate'), ['VisitDate'], unique=False)

    op.create_table('custom_field_values',
    sa.Column('ValueID', sa.Integer(), nullable=False),
    sa.Column('FieldID', sa.Integer(), nullable=False),
    sa.Column('RecordID', sa.Integer(), nullable=False),
    sa.Column('Value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['FieldID'], ['custom_fields.FieldID'], ),
    sa.PrimaryKeyConstraint('ValueID')
    )
    op.create_table('email_logs',
    sa.Column('EmailID', sa.Integer(), nullable=False),
    sa.Column('CommunicationID', sa.Integer(), nullable=False),
    sa.Column('Recipient', sa.String(length=120), nullable=True),
    sa.Column('Status', sa.String(length=40), nullable=True),
    sa.Column('Error', sa.String(length=255), nullable=True),
    sa.Column('SentAt', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CommunicationID'], ['communications.CommunicationID'], ),
    sa.PrimaryKeyConstraint('EmailID')
    )
    op.create_table('maintenance_logs',
    sa.Column('MaintenanceID', sa.Integer(), nullable=False),
    sa.Column('ItemID', sa.Integer(), nullable=False),
    sa.Column('ServiceDate', sa.Date(), nullable=True),
    sa.Column('Remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ItemID'], ['inventory_items.ItemID'], ),
    sa.PrimaryKeyConstraint('MaintenanceID')
    )
    op.create_table('members',
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('MemberNumber', sa.String(length=40), nullable=True),
    sa.Column('FirstName', sa.String(length=80), nullable=False),
    sa.Column('MiddleName', sa.String(length=80), nullable=True),
    sa.Column('LastName', sa.String(length=80), nullable=False),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('Gender', sa.String(length=20), nullable=True),
    sa.Column('Nationality', sa.String(length=80), nullable=True),
    sa.Column('MaritalStatus', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('PersonalEmail', sa.String(length=120), nullable=True),
    sa.Column('GSMNumber', sa.String(length=40), nullable=True),
    sa.Column('WhatsAppNumber', sa.String(length=40), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('Employed', sa.Boolean(), nullable=True),
    sa.Column('Occupation', sa.String(length=120), nullable=True),
    sa.Column('EmployerName', sa.String(length=120), nullable=True),
    sa.Column('PlaceOfWork', sa.String(length=120), nullable=True),
    sa.Column('ProfessionalCategory', sa.String(length=80), nullable=True),
    sa.Column('BaptismDate', sa.Date(), nullable=True),
    sa.Column('JoiningDate', sa.Date(), nullable=True),
    sa.Column('MembershipStatus', sa.String(length=40), nullable=True),
    sa.Column('NewMemberStatus', sa.Boolean(), nullable=True),
    sa.Column('WelfareRequired', sa.Boolean(), nullable=True),
    sa.Column('MotherChurchName', sa.String(length=120), nullable=True),
    sa.Column('MotherChurchAddress', sa.String(length=255), nullable=True),
    sa.Column('MotherChurchCountry', sa.String(length=80), nullable=True),
    sa.Column('CareCellID', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CareCellID'], ['care_cells.CareCellID'], ),
    sa.PrimaryKeyConstraint('MemberID')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_MemberNumber'), ['MemberNumber'], unique=True)

    op.create_table('mission_support',
    sa.Column('SupportID', sa.Integer(), nullable=False),
    sa.Column('MissionID', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('SupportDate', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MissionID'], ['missions.MissionID'], ),
    sa.PrimaryKeyConstraint('SupportID')
    )
    with op.batch_alter_table('mission_support', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_support_SupportDate'), ['SupportDate'], unique=False)

    op.create_table('outreach_visitors',
    sa.Column('OutreachVisitorID', sa.Integer(), nullable=False),
    sa.Column('OutreachID', sa.Integer(), nullable=False),
    sa.Column('VisitorID', sa.Integer(), nullable=False),
    sa.Column('FollowupStatus', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['OutreachID'], ['outreach_programs.OutreachID'], ),
    sa.ForeignKeyConstraint(['VisitorID'], ['visitors.VisitorID'], ),
    sa.PrimaryKeyConstraint('OutreachVisitorID')
    )
    op.create_table('role_permissions',
    sa.Column('RolePermissionID', sa.Integer(), nullable=False),
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['PermissionID'], ['permissions.PermissionID'], ),
    sa.ForeignKeyConstraint(['RoleID'], ['roles.RoleID'], ),
    sa.PrimaryKeyConstraint('RolePermissionID'),
    sa.UniqueConstraint('RoleID', 'PermissionID', name='uq_role_permission')
    )
    op.create_table('sms_logs',
    sa.Column('SMSID', sa.Integer(), nullable=False),
    sa.Column('CommunicationID', sa.Integer(), nullable=False),
    sa.Column('Recipient', sa.String(length=40), nullable=True),
    sa.Column('Status', sa.String(length=40), nullable=True),
    sa.Column('ProviderSid', sa.String(length=80), nullable=True),
    sa.Column('Error', sa.String(length=255), nullable=True),
    sa.Column('SentAt', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CommunicationID'], ['communications.CommunicationID'], ),
    sa.PrimaryKeyConstraint('SMSID')
    )
    op.create_table('visitor_followups',
    sa.Column('FollowupID', sa.Integer(), nullable=False),
    sa.Column('VisitorID', sa.Integer(), nullable=False),
    sa.Column('FollowupDate', sa.Date(), nullable=True),
    sa.Column('AssignedWorker', sa.String(length=120), nullable=True),
    sa.Column('Outcome', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['VisitorID'], ['visitors.VisitorID'], ),
    sa.PrimaryKeyConstraint('FollowupID')
    )
    op.create_table('whatsapp_logs',
    sa.Column('WhatsAppID', sa.Integer(), nullable=False),
    sa.Column('CommunicationID', sa.Integer(), nullable=False),
    sa.Column('Recipient', sa.String(length=40), nullable=True),
    sa.Column('Status', sa.String(length=40), nullable=True),
    sa.Column('ProviderSid', sa.String(length=80), nullable=True),
    sa.Column('Error', sa.String(length=255), nullable=True),
    sa.Column('SentAt', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CommunicationID'], ['communications.CommunicationID'], ),
    sa.PrimaryKeyConstraint('WhatsAppID')
    )
    op.create_table('attendance',
    sa.Column('AttendanceID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('EventID', sa.Integer(), nullable=True),
    sa.Column('AttendanceDate', sa.Date(), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=True),
    sa.Column('CheckInTime', sa.Time(), nullable=True),
    sa.Column('Notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['EventID'], ['events.EventID'], ),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('AttendanceID')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_AttendanceDate'), ['AttendanceDate'], unique=False)

    op.create_table('carecell_members',
    sa.Column('CellMemberID', sa.Integer(), nullable=False),
    sa.Column('CareCellID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CareCellID'], ['care_cells.CareCellID'], ),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('CellMemberID')
    )
    op.create_table('children',
    sa.Column('ChildID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=80), nullable=False),
    sa.Column('LastName', sa.String(length=80), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('Gender', sa.String(length=20), nullable=True),
    sa.Column('School', sa.String(length=120), nullable=True),
    sa.Column('SchoolClass', sa.String(length=80), nullable=True),
    sa.Column('BaptismStatus', sa.String(length=40), nullable=True),
    sa.Column('MembershipStatus', sa.String(length=40), nullable=True),
    sa.Column('PhotoPath', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('ChildID')
    )
    op.create_table('counselling_cases',
    sa.Column('CaseID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=True),
    sa.Column('CounsellorID', sa.Integer(), nullable=True),
    sa.Column('CaseType', sa.String(length=80), nullable=True),
    sa.Column('SessionDate', sa.Date(), nullable=True),
    sa.Column('Summary', sa.Text(), nullable=True),
    sa.Column('ConfidentialNotes', sa.Text(), nullable=True),
    sa.Column('Status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CounsellorID'], ['members.MemberID'], ),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('CaseID')
    )
    op.create_table('donations',
    sa.Column('DonationID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=True),
    sa.Column('DonorName', sa.String(length=120), nullable=True),
    sa.Column('Amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('Purpose', sa.String(length=150), nullable=True),
    sa.Column('DonationDate', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('DonationID')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_DonationDate'), ['DonationDate'], unique=False)

    op.create_table('event_assignments',
    sa.Column('AssignmentID', sa.Integer(), nullable=False),
    sa.Column('EventID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('AssignedRole', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['EventID'], ['events.EventID'], ),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('AssignmentID')
    )
    op.create_table('form_responses',
    sa.Column('ResponseID', sa.Integer(), nullable=False),
    sa.Column('FormID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=True),
    sa.Column('RawData', sa.Text(), nullable=True),
    sa.Column('Imported', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['FormID'], ['google_forms.FormID'], ),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('ResponseID')
    )
    op.create_table('friday_school_classes',
    sa.Column('ClassID', sa.Integer(), nullable=False),
    sa.Column('ClassName', sa.String(length=120), nullable=False),
    sa.Column('TeacherID', sa.Integer(), nullable=True),
    sa.Column('AssistantTeacherID', sa.Integer(), nullable=True),
    sa.Column('AgeGroup', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AssistantTeacherID'], ['members.MemberID'], ),
    sa.ForeignKeyConstraint(['TeacherID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('ClassID')
    )
    op.create_table('member_documents',
    sa.Column('DocumentID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('DocumentType', sa.String(length=80), nullable=True),
    sa.Column('FileName', sa.String(length=255), nullable=True),
    sa.Column('FilePath', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('DocumentID')
    )
    op.create_table('member_leadership',
    sa.Column('EntryID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('LeadershipRoleID', sa.Integer(), nullable=False),
    sa.Column('AppointmentDate', sa.Date(), nullable=True),
    sa.Column('Department', sa.String(length=120), nullable=True),
    sa.Column('Responsibilities', sa.Text(), nullable=True),
    sa.Column('TermDuration', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['LeadershipRoleID'], ['leadership_roles.LeadershipRoleID'], ),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('EntryID')
    )
    op.create_table('member_photos',
    sa.Column('PhotoID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('PhotoType', sa.String(length=40), nullable=True),
    sa.Column('FilePath', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('PhotoID')
    )
    op.create_table('member_training',
    sa.Column('MemberTrainingID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('CourseID', sa.Integer(), nullable=False),
    sa.Column('CompletionStatus', sa.String(length=40), nullable=True),
    sa.Column('CompletionDate', sa.Date(), nullable=True),
    sa.Column('CertificateNumber', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CourseID'], ['training_courses.CourseID'], ),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('MemberTrainingID')
    )
    op.create_table('ministry_members',
    sa.Column('MinistryMemberID', sa.Integer(), nullable=False),
    sa.Column('MinistryID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('MinistryRole', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.ForeignKeyConstraint(['MinistryID'], ['ministries.MinistryID'], ),
    sa.PrimaryKeyConstraint('MinistryMemberID')
    )
    op.create_table('pastors',
    sa.Column('PastorID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=True),
    sa.Column('Position', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('PastorID')
    )
    op.create_table('prayer_requests',
    sa.Column('PrayerRequestID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=True),
    sa.Column('RequestDetails', sa.Text(), nullable=False),
    sa.Column('Category', sa.String(length=80), nullable=True),
    sa.Column('AssignedTeam', sa.String(length=120), nullable=True),
    sa.Column('Status', sa.String(length=40), nullable=True),
    sa.Column('Testimony', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('PrayerRequestID')
    )
    op.create_table('spouses',
    sa.Column('SpouseID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(length=80), nullable=True),
    sa.Column('LastName', sa.String(length=80), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('Gender', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Phone', sa.String(length=40), nullable=True),
    sa.Column('Occupation', sa.String(length=120), nullable=True),
    sa.Column('PhotoPath', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('SpouseID')
    )
    op.create_table('tithes',
    sa.Column('TitheID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=True),
    sa.Column('Amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('PaymentDate', sa.Date(), nullable=True),
    sa.Column('PaymentMethod', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('TitheID')
    )
    with op.batch_alter_table('tithes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tithes_PaymentDate'), ['PaymentDate'], unique=False)

    op.create_table('users',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=80), nullable=False),
    sa.Column('PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('RoleID', sa.Integer(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=True),
    sa.Column('TotpSecret', sa.String(length=64), nullable=True),
    sa.Column('TwoFAEnabled', sa.Boolean(), nullable=False),
    sa.Column('FailedLoginCount', sa.Integer(), nullable=False),
    sa.Column('LockedUntil', sa.DateTime(), nullable=True),
    sa.Column('LastLoginAt', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.ForeignKeyConstraint(['RoleID'], ['roles.RoleID'], ),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('welfare_requests',
    sa.Column('WelfareID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=True),
    sa.Column('SupportType', sa.String(length=80), nullable=True),
    sa.Column('Amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('Status', sa.String(length=40), nullable=True),
    sa.Column('ApprovedBy', sa.String(length=120), nullable=True),
    sa.Column('FollowupActions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('WelfareID')
    )
    op.create_table('audit_logs',
    sa.Column('AuditID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('Action', sa.String(length=40), nullable=True),
    sa.Column('TableName', sa.String(length=80), nullable=True),
    sa.Column('RecordID', sa.String(length=40), nullable=True),
    sa.Column('Changes', sa.Text(), nullable=True),
    sa.Column('ActionDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], ),
    sa.PrimaryKeyConstraint('AuditID')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_ActionDate'), ['ActionDate'], unique=False)

    op.create_table('baby_dedications',
    sa.Column('DedicationID', sa.Integer(), nullable=False),
    sa.Column('ChildID', sa.Integer(), nullable=True),
    sa.Column('DedicationDate', sa.Date(), nullable=True),
    sa.Column('PastorID', sa.Integer(), nullable=True),
    sa.Column('CertificateIssued', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ChildID'], ['children.ChildID'], ),
    sa.ForeignKeyConstraint(['PastorID'], ['pastors.PastorID'], ),
    sa.PrimaryKeyConstraint('DedicationID')
    )
    op.create_table('counselling_followups',
    sa.Column('FollowupID', sa.Integer(), nullable=False),
    sa.Column('CaseID', sa.Integer(), nullable=False),
    sa.Column('FollowupDate', sa.Date(), nullable=True),
    sa.Column('AssignedCounsellorID', sa.Integer(), nullable=True),
    sa.Column('Reminder', sa.Boolean(), nullable=True),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AssignedCounsellorID'], ['members.MemberID'], ),
    sa.ForeignKeyConstraint(['CaseID'], ['counselling_cases.CaseID'], ),
    sa.PrimaryKeyConstraint('FollowupID')
    )
    op.create_table('friday_school_activities',
    sa.Column('ActivityID', sa.Integer(), nullable=False),
    sa.Column('ClassID', sa.Integer(), nullable=True),
    sa.Column('ActivityName', sa.String(length=150), nullable=False),
    sa.Column('ActivityDate', sa.Date(), nullable=True),
    sa.Column('TeacherNotes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ClassID'], ['friday_school_classes.ClassID'], ),
    sa.PrimaryKeyConstraint('ActivityID')
    )
    op.create_table('friday_school_students',
    sa.Column('StudentID', sa.Integer(), nullable=False),
    sa.Column('ChildID', sa.Integer(), nullable=True),
    sa.Column('ClassID', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ChildID'], ['children.ChildID'], ),
    sa.ForeignKeyConstraint(['ClassID'], ['friday_school_classes.ClassID'], ),
    sa.PrimaryKeyConstraint('StudentID')
    )
    op.create_table('sermons',
    sa.Column('SermonID', sa.Integer(), nullable=False),
    sa.Column('EventID', sa.Integer(), nullable=True),
    sa.Column('PastorID', sa.Integer(), nullable=True),
    sa.Column('SermonTitle', sa.String(length=200), nullable=False),
    sa.Column('ScriptureReference', sa.String(length=200), nullable=True),
    sa.Column('ServiceDate', sa.Date(), nullable=True),
    sa.Column('ServiceType', sa.String(length=80), nullable=True),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['EventID'], ['events.EventID'], ),
    sa.ForeignKeyConstraint(['PastorID'], ['pastors.PastorID'], ),
    sa.PrimaryKeyConstraint('SermonID')
    )
    with op.batch_alter_table('sermons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sermons_ServiceDate'), ['ServiceDate'], unique=False)

    op.create_table('friday_school_attendance',
    sa.Column('AttendanceID', sa.Integer(), nullable=False),
    sa.Column('StudentID', sa.Integer(), nullable=False),
    sa.Column('AttendanceDate', sa.Date(), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['StudentID'], ['friday_school_students.StudentID'], ),
    sa.PrimaryKeyConstraint('AttendanceID')
    )
    with op.batch_alter_table('friday_school_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friday_school_attendance_AttendanceDate'), ['AttendanceDate'], unique=False)

    op.create_table('friday_school_performance',
    sa.Column('PerformanceID', sa.Integer(), nullable=False),
    sa.Column('StudentID', sa.Integer(), nullable=False),
    sa.Column('Assessment', sa.String(length=120), nullable=True),
    sa.Column('Behavior', sa.String(length=120), nullable=True),
    sa.Column('Participation', sa.String(length=120), nullable=True),
    sa.Column('Achievements', sa.Text(), nullable=True),
    sa.Column('Remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['StudentID'], ['friday_school_students.StudentID'], ),
    sa.PrimaryKeyConstraint('PerformanceID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friday_school_performance')
    with op.batch_alter_table('friday_school_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friday_school_attendance_AttendanceDate'))

    op.drop_table('friday_school_attendance')
    with op.batch_alter_table('sermons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sermons_ServiceDate'))

    op.drop_table('sermons')
    op.drop_table('friday_school_students')
    op.drop_table('friday_school_activities')
    op.drop_table('counselling_followups')
    op.drop_table('baby_dedications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_ActionDate'))

    op.drop_table('audit_logs')
    op.drop_table('welfare_requests')
    op.drop_table('users')
    with op.batch_alter_table('tithes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tithes_PaymentDate'))

    op.drop_table('tithes')
    op.drop_table('spouses')
    op.drop_table('prayer_requests')
    op.drop_table('pastors')
    op.drop_table('ministry_members')
    op.drop_table('member_training')
    op.drop_table('member_photos')
    op.drop_table('member_leadership')
    op.drop_table('member_documents')
    op.drop_table('friday_school_classes')
    op.drop_table('form_responses')
    op.drop_table('event_assignments')
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_DonationDate'))

    op.drop_table('donations')
    op.drop_table('counselling_cases')
    op.drop_table('children')
    op.drop_table('carecell_members')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_AttendanceDate'))

    op.drop_table('attendance')
    op.drop_table('whatsapp_logs')
    op.drop_table('visitor_followups')
    op.drop_table('sms_logs')
    op.drop_table('role_permissions')
    op.drop_table('outreach_visitors')
    with op.batch_alter_table('mission_support', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_support_SupportDate'))

    op.drop_table('mission_support')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_MemberNumber'))

    op.drop_table('members')
    op.drop_table('maintenance_logs')
    op.drop_table('email_logs')
    op.drop_table('custom_field_values')
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitors_VisitDate'))

    op.drop_table('visitors')
    op.drop_table('training_courses')
    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_ModuleName'))

    op.drop_table('permissions')
    op.drop_table('outreach_programs')
    with op.batch_alter_table('offerings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offerings_ServiceDate'))

    op.drop_table('offerings')
    op.drop_table('missions')
    op.drop_table('ministries')
    op.drop_table('leadership_roles')
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_AssetCode'))

    op.drop_table('inventory_items')
    op.drop_table('google_forms')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_EventDate'))

    op.drop_table('events')
    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_fields_Module'))

    op.drop_table('custom_fields')
    op.drop_table('communications')
    op.drop_table('care_cells')
    op.drop_table('backups')
    # ### end Alembic commands ###
