"""add_new_erp_modules

Revision ID: f3e2a6829c44
Revises: c1f63f26d538
Create Date: 2026-09-01 21:48:47.670836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e2a6829c44'
down_revision = 'c1f63f26d538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('BuildingID', sa.Integer(), nullable=False),
    sa.Column('BuildingName', sa.String(length=120), nullable=False),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('ContactPerson', sa.String(length=120), nullable=True),
    sa.Column('ContactPhone', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('BuildingID')
    )
    op.create_table('external_churches',
    sa.Column('ExternalChurchID', sa.Integer(), nullable=False),
    sa.Column('ChurchName', sa.String(length=150), nullable=False),
    sa.Column('ContactPerson', sa.String(length=120), nullable=True),
    sa.Column('Phone', sa.String(length=40), nullable=True),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ExternalChurchID')
    )
    op.create_table('rooms',
    sa.Column('RoomID', sa.Integer(), nullable=False),
    sa.Column('BuildingID', sa.Integer(), nullable=False),
    sa.Column('RoomName', sa.String(length=120), nullable=False),
    sa.Column('Floor', sa.String(length=40), nullable=True),
    sa.Column('Capacity', sa.Integer(), nullable=True),
    sa.Column('RoomType', sa.String(length=80), nullable=True),
    sa.Column('RentalRate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('DepositAmount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Status', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['BuildingID'], ['buildings.BuildingID'], ),
    sa.PrimaryKeyConstraint('RoomID')
    )
    op.create_table('discipleship_progress',
    sa.Column('ProgressID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('Level1Status', sa.String(length=40), nullable=True),
    sa.Column('Level1CompletionDate', sa.Date(), nullable=True),
    sa.Column('Level2Status', sa.String(length=40), nullable=True),
    sa.Column('Level2CompletionDate', sa.Date(), nullable=True),
    sa.Column('Level3Status', sa.String(length=40), nullable=True),
    sa.Column('Level3CompletionDate', sa.Date(), nullable=True),
    sa.Column('Level4Status', sa.String(length=40), nullable=True),
    sa.Column('Level4CompletionDate', sa.Date(), nullable=True),
    sa.Column('Facilitator', sa.String(length=120), nullable=True),
    sa.Column('Remarks', sa.Text(), nullable=True),
    sa.Column('CertificateNumber', sa.String(length=80), nullable=True),
    sa.Column('CertificatePath', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('ProgressID'),
    sa.UniqueConstraint('MemberID')
    )
    op.create_table('member_exits',
    sa.Column('ExitID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('LastDateInChurch', sa.Date(), nullable=True),
    sa.Column('ExitCategory', sa.String(length=80), nullable=False),
    sa.Column('ExitReason', sa.Text(), nullable=True),
    sa.Column('DepartureNotes', sa.Text(), nullable=True),
    sa.Column('ExitDate', sa.DateTime(), nullable=True),
    sa.Column('DestCountry', sa.String(length=80), nullable=True),
    sa.Column('DestState', sa.String(length=120), nullable=True),
    sa.Column('DestCity', sa.String(length=120), nullable=True),
    sa.Column('DestAddress', sa.String(length=255), nullable=True),
    sa.Column('DestPostalCode', sa.String(length=20), nullable=True),
    sa.Column('CompanyName', sa.String(length=150), nullable=True),
    sa.Column('CompanyPosition', sa.String(length=120), nullable=True),
    sa.Column('CompanyEmail', sa.String(length=120), nullable=True),
    sa.Column('CompanyContact', sa.String(length=40), nullable=True),
    sa.Column('NewMobile', sa.String(length=40), nullable=True),
    sa.Column('NewWhatsApp', sa.String(length=40), nullable=True),
    sa.Column('NewPersonalEmail', sa.String(length=120), nullable=True),
    sa.Column('NewAlternateEmail', sa.String(length=120), nullable=True),
    sa.Column('NewChurchName', sa.String(length=150), nullable=True),
    sa.Column('NewChurchAddress', sa.String(length=255), nullable=True),
    sa.Column('NewPastorName', sa.String(length=120), nullable=True),
    sa.Column('NewPastorContact', sa.String(length=40), nullable=True),
    sa.Column('NewPastorEmail', sa.String(length=120), nullable=True),
    sa.Column('WillingToBeContacted', sa.Boolean(), nullable=True),
    sa.Column('PreferredCommunication', sa.String(length=40), nullable=True),
    sa.Column('FollowupFrequency', sa.String(length=40), nullable=True),
    sa.Column('EmergencyContactPerson', sa.String(length=120), nullable=True),
    sa.Column('EmergencyRelationship', sa.String(length=80), nullable=True),
    sa.Column('EmergencyMobile', sa.String(length=40), nullable=True),
    sa.Column('EmergencyWhatsApp', sa.String(length=40), nullable=True),
    sa.Column('EmergencyEmail', sa.String(length=120), nullable=True),
    sa.Column('EmergencyAddress', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('ExitID')
    )
    op.create_table('ministry_movements',
    sa.Column('MovementID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('MovementType', sa.String(length=40), nullable=False),
    sa.Column('PreviousMinistryID', sa.Integer(), nullable=True),
    sa.Column('PreviousRole', sa.String(length=80), nullable=True),
    sa.Column('NewMinistryID', sa.Integer(), nullable=True),
    sa.Column('NewRole', sa.String(length=80), nullable=True),
    sa.Column('EffectiveDate', sa.Date(), nullable=False),
    sa.Column('LastDatePrevious', sa.Date(), nullable=True),
    sa.Column('Reason', sa.Text(), nullable=True),
    sa.Column('ApprovedBy', sa.String(length=120), nullable=True),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.ForeignKeyConstraint(['NewMinistryID'], ['ministries.MinistryID'], ),
    sa.ForeignKeyConstraint(['PreviousMinistryID'], ['ministries.MinistryID'], ),
    sa.PrimaryKeyConstraint('MovementID')
    )
    op.create_table('ordinations',
    sa.Column('OrdinationID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('IsOrdained', sa.Boolean(), nullable=True),
    sa.Column('OrdinationDate', sa.Date(), nullable=True),
    sa.Column('OrdainingChurch', sa.String(length=150), nullable=True),
    sa.Column('OrdainingOrganization', sa.String(length=150), nullable=True),
    sa.Column('OrdainingAuthority', sa.String(length=150), nullable=True),
    sa.Column('CertificateNumber', sa.String(length=80), nullable=True),
    sa.Column('CertificatePath', sa.String(length=255), nullable=True),
    sa.Column('Remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('OrdinationID'),
    sa.UniqueConstraint('MemberID')
    )
    op.create_table('previous_church_experiences',
    sa.Column('ExperienceID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('ChurchName', sa.String(length=150), nullable=False),
    sa.Column('Denomination', sa.String(length=120), nullable=True),
    sa.Column('City', sa.String(length=120), nullable=True),
    sa.Column('Country', sa.String(length=80), nullable=True),
    sa.Column('ServiceStartDate', sa.Date(), nullable=True),
    sa.Column('ServiceEndDate', sa.Date(), nullable=True),
    sa.Column('LeadershipRole', sa.String(length=80), nullable=True),
    sa.Column('MinistryServed', sa.String(length=120), nullable=True),
    sa.Column('Responsibilities', sa.Text(), nullable=True),
    sa.Column('TotalDuration', sa.String(length=80), nullable=True),
    sa.Column('ReferenceContact', sa.String(length=120), nullable=True),
    sa.Column('ReferencePhone', sa.String(length=40), nullable=True),
    sa.Column('ReferenceEmail', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('ExperienceID')
    )
    op.create_table('room_bookings',
    sa.Column('BookingID', sa.Integer(), nullable=False),
    sa.Column('BookingNumber', sa.String(length=40), nullable=True),
    sa.Column('RoomID', sa.Integer(), nullable=False),
    sa.Column('RequestingChurchID', sa.Integer(), nullable=True),
    sa.Column('Ministry', sa.String(length=120), nullable=True),
    sa.Column('EventName', sa.String(length=150), nullable=False),
    sa.Column('EventType', sa.String(length=80), nullable=True),
    sa.Column('Recurrence', sa.String(length=40), nullable=True),
    sa.Column('StartDate', sa.Date(), nullable=False),
    sa.Column('EndDate', sa.Date(), nullable=False),
    sa.Column('StartTime', sa.Time(), nullable=False),
    sa.Column('EndTime', sa.Time(), nullable=False),
    sa.Column('NumParticipants', sa.Integer(), nullable=True),
    sa.Column('RentalAmount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('SecurityDeposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Taxes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('FinalCharge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('InvoiceNumber', sa.String(length=40), nullable=True),
    sa.Column('PaymentStatus', sa.String(length=40), nullable=True),
    sa.Column('BookingStatus', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['RequestingChurchID'], ['external_churches.ExternalChurchID'], ),
    sa.ForeignKeyConstraint(['RoomID'], ['rooms.RoomID'], ),
    sa.PrimaryKeyConstraint('BookingID')
    )
    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_bookings_BookingNumber'), ['BookingNumber'], unique=True)
        batch_op.create_index(batch_op.f('ix_room_bookings_StartDate'), ['StartDate'], unique=False)

    op.create_table('eligibility_overrides',
    sa.Column('OverrideID', sa.Integer(), nullable=False),
    sa.Column('MemberID', sa.Integer(), nullable=False),
    sa.Column('OverrideReason', sa.Text(), nullable=False),
    sa.Column('ApprovedByUserID', sa.Integer(), nullable=False),
    sa.Column('OverrideDate', sa.DateTime(), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ApprovedByUserID'], ['users.UserID'], ),
    sa.ForeignKeyConstraint(['MemberID'], ['members.MemberID'], ),
    sa.PrimaryKeyConstraint('OverrideID')
    )
    with op.batch_alter_table('member_leadership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('EndDate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ActiveStatus', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ReportingTo', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('LeadershipLevel', sa.String(length=80), nullable=True))

    with op.batch_alter_table('member_training', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CertificationDate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('TrainingHours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('DocumentPath', sa.String(length=255), nullable=True))

    with op.batch_alter_table('ministry_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('JoinDate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('AppointmentDate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ActiveFlag', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('Status', sa.String(length=40), nullable=True))

    with op.batch_alter_table('training_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TrainingType', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('Provider', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('OrganizingChurch', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('SponsoringChurch', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('Location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('TotalHours', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_courses', schema=None) as batch_op:
        batch_op.drop_column('TotalHours')
        batch_op.drop_column('Location')
        batch_op.drop_column('SponsoringChurch')
        batch_op.drop_column('OrganizingChurch')
        batch_op.drop_column('Provider')
        batch_op.drop_column('TrainingType')

    with op.batch_alter_table('ministry_members', schema=None) as batch_op:
        batch_op.drop_column('Status')
        batch_op.drop_column('ActiveFlag')
        batch_op.drop_column('AppointmentDate')
        batch_op.drop_column('JoinDate')

    with op.batch_alter_table('member_training', schema=None) as batch_op:
        batch_op.drop_column('DocumentPath')
        batch_op.drop_column('TrainingHours')
        batch_op.drop_column('CertificationDate')

    with op.batch_alter_table('member_leadership', schema=None) as batch_op:
        batch_op.drop_column('LeadershipLevel')
        batch_op.drop_column('ReportingTo')
        batch_op.drop_column('ActiveStatus')
        batch_op.drop_column('EndDate')

    op.drop_table('eligibility_overrides')
    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_bookings_StartDate'))
        batch_op.drop_index(batch_op.f('ix_room_bookings_BookingNumber'))

    op.drop_table('room_bookings')
    op.drop_table('previous_church_experiences')
    op.drop_table('ordinations')
    op.drop_table('ministry_movements')
    op.drop_table('member_exits')
    op.drop_table('discipleship_progress')
    op.drop_table('rooms')
    op.drop_table('external_churches')
    op.drop_table('buildings')
    # ### end Alembic commands ###
